<?php

return [
    'units' => [
        [
            'id' => 0,
            'street' => 'SMBZ',
            'name' => 'Mirdif City Centre',
            'location' => [
                'Sheikh Mohammed',
                'Bin Zayed Rd',
                'before Ras Al Khor Rd exit',
            ],
            'media' => 'Hoarding',
            'traffic' => 700000,
            'size' => '80x12 m / front lit',
            'media_kit_url' => 'assets/pdf/smbz-mirdif-mediakit.pdf',
            'landmarks' => [
                'Abu Dhabi,',
                'Al Maktoum Airport,',
                'Dubai International City,',
                'Mirdif City Centre,',
                'Dragon Mart,',
                'Global Village,',
                'Nad Al Sheba,',
                'Al Khor',
            ],
            'video_urls' => ['assets/videos/MBZ Mirdif.mp4'],
            'photos' => [
                'assets/img/smbz-mirdif/IMG_6012.webp',
                'assets/img/smbz-mirdif/IMG_7311.webp',
            ],
            'hero_photo' => 'assets/img/smbz-road-hero.jpg',
            'coords' => [55.3949963, 25.1897052],
        ],
        [
            'id' => 1,
            'street' => 'SMBZ',
            'name' => 'Arabian Ranches',
            'location' => [
                'Sheikh Mohammed',
                'Bin Zayed Rd',
                'Arabian Ranches',
            ],
            'media' => 'Hoarding',
            'traffic' => 700000,
            'size' => '50x12 m / front lit',
            'media_kit_url' => 'assets/pdf/smbz-arabian-mediakit.pdf',
            'landmarks' => [
                'Abu Dhabi,',
                'Al Maktoum Airport,',
                'Dubai Sports City,',
                'Dubai Autodrome,',
                'Arabian Ranches,',
                'JVC,',
                'Al Barsha South,',
                'Dubai Butterfly Garden',
            ],
            'video_urls' => ['assets/videos/Fakhruddin_Properties_Arabian_Ranches_v.mp4'],
            'photos' => [
                'assets/img/smbz-arabian/IMG_2662.jpeg',
                'assets/img/smbz-arabian/IMG_4386.jpeg',
            ],
            'hero_photo' => 'assets/img/smbz-road-hero.jpg',
            'coords' => [55.2678473, 25.0578632],
        ],
        [
            'id' => 2,
            'street' => 'AL AIN',
            'name' => 'Nad Al Sheba',
            'location' => [
                'Al Ain Road between',
                'Nad Al Sheba 1',
                'and Nad Al Sheba 2',
            ],
            'media' => 'Hoarding',
            'traffic' => 600000,
            'size' => '50x12 m / front lit',
            'media_kit_url' => 'assets/pdf/al-ain-mediakit.pdf',
            'landmarks' => [
                'Nad Al Sheba 1,',
                'Nad Al Sheba 2,',
                'Ras Al Khor,',
                'Dubai Racing Club',
            ],
            'video_urls' => ['assets/videos/Fakhruddin_Properties.mp4'],
            'photos' => [
                'assets/img/al-ain/IMG_5472.webp',
                'assets/img/al-ain/IMG_5551.webp',
            ],
            'hero_photo' => 'assets/img/al-ain-road-hero.jpg',
            'coords' => [55.3291623, 25.1619682],
        ],
        [
            'id' => 3,
            'street' => 'SZR',
            'name' => '#1 Palm Jebel Ali',  
            'location' => [
                'Sheikh Zayed Rd',
                'Palm Jebel Ali',
            ],
            'media' => 'Hoarding',
            'traffic' => 800000,
            'size' => '50x12 m / front lit',
            'media_kit_url' => 'assets/pdf/szr-palm-1-mediakit.pdf',
            'landmarks' => [
                'Abu Dhabi,',
                'Al Maktoum Airport,',
                'Palm Jebel Ali,',
                'Downtown Jebel Ali,',
                'Motiongate,',
                'Legoland,',
                'The Outlet Village,',
                'Emarat,',
                'ENOC',
            ],
            'video_urls' => ['assets/videos/nb_video.mp4'],
            'photos' => [
                'assets/img/szr-palm-1/IMG_7945.webp',
                'assets/img/szr-palm-1/IMG_7976.webp',
            ],
            'hero_photo' => 'assets/img/beirut-street-hero.jpg',
            'coords' => [55.0226873, 24.9339072],
        ],
        [
            'id' => 4,
            'street' => 'SZR',
            'name' => '#2 Palm Jebel Ali',
            'location' => [
                'Sheikh Zayed Rd',
                'Palm Jebel Ali',
            ],
            'media' => 'Hoarding',
            'traffic' => 800000,
            'size' => '50x12 m / front lit',
            'media_kit_url' => 'assets/pdf/szr-palm-2-mediakit.pdf',
            'landmarks' => [
                'Abu Dhabi,',
                'Al Maktoum Airport,',
                'Palm Jebel Ali,',
                'Downtown Jebel Ali,',
                'Motiongate,',
                'Legoland,',
                'The Outlet Village,',
                'Emarat,',
                'ENOC',
            ],
            'video_urls' => ['assets/videos/palm_jebal_ali.mp4'],
            'photos' => [
                'assets/img/szr-palm-2/IMG_5352.webp',
                'assets/img/szr-palm-2/IMG_5361.webp',
            ],
            'hero_photo' => 'assets/img/beirut-street-hero.jpg',
            'coords' => [55.0447173, 24.9415782],
        ],
        [
            'id' => 5,
            'street' => 'BEIRUT STREET',
            'name' => 'Madina Mall',
            'location' => 'Beirut street',
            'media' => 'Unipole',
            'traffic' => 350000,
            'size' => '12x6 m / 2 faces / back lit',
            'media_kit_url' => 'assets/pdf/beirut-mediakit.pdf',
            'landmarks' => [
                'Madina Mall,',
                'Aster Hospital,',
                'Haleb str,',
                'ADNOC,',
                'Emarat',
            ],
            'video_urls' => ['assets/videos/video.mp4'],
            'photos' => [
                'assets/img/beirut/face_a2.webp',
                'assets/img/beirut/IMG_7818.webp',
            ],
            'hero_photo' => 'assets/img/beirut-street-hero.jpg',
            'coords' => [55.396133, 25.2799125],
        ],
    ],
];

